'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ActiveCaption_Sync() As Boolean
            Get
                Return CType(Me("ActiveCaption_Sync"),Boolean)
            End Get
            Set
                Me("ActiveCaption_Sync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ActiveCaption_SetBrit() As Boolean
            Get
                Return CType(Me("ActiveCaption_SetBrit"),Boolean)
            End Get
            Set
                Me("ActiveCaption_SetBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.7")>  _
        Public Property ActiveCaption_UsrBrit() As Double
            Get
                Return CType(Me("ActiveCaption_UsrBrit"),Double)
            End Get
            Set
                Me("ActiveCaption_UsrBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ActiveCaptionGradient_Sync() As Boolean
            Get
                Return CType(Me("ActiveCaptionGradient_Sync"),Boolean)
            End Get
            Set
                Me("ActiveCaptionGradient_Sync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ActiveCaptionGradient_SetBrit() As Boolean
            Get
                Return CType(Me("ActiveCaptionGradient_SetBrit"),Boolean)
            End Get
            Set
                Me("ActiveCaptionGradient_SetBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.7")>  _
        Public Property ActiveCaptionGradient_UsrBrit() As Double
            Get
                Return CType(Me("ActiveCaptionGradient_UsrBrit"),Double)
            End Get
            Set
                Me("ActiveCaptionGradient_UsrBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Hilight_Sync() As Boolean
            Get
                Return CType(Me("Hilight_Sync"),Boolean)
            End Get
            Set
                Me("Hilight_Sync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hilight_SetBrit() As Boolean
            Get
                Return CType(Me("Hilight_SetBrit"),Boolean)
            End Get
            Set
                Me("Hilight_SetBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.5")>  _
        Public Property Hilight_UsrBrit() As Double
            Get
                Return CType(Me("Hilight_UsrBrit"),Double)
            End Get
            Set
                Me("Hilight_UsrBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MenuHilight_Sync() As Boolean
            Get
                Return CType(Me("MenuHilight_Sync"),Boolean)
            End Get
            Set
                Me("MenuHilight_Sync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MenuHilight_SetBrit() As Boolean
            Get
                Return CType(Me("MenuHilight_SetBrit"),Boolean)
            End Get
            Set
                Me("MenuHilight_SetBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.5")>  _
        Public Property MenuHilight_UsrBrit() As Double
            Get
                Return CType(Me("MenuHilight_UsrBrit"),Double)
            End Get
            Set
                Me("MenuHilight_UsrBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property HotTracking_Sync() As Boolean
            Get
                Return CType(Me("HotTracking_Sync"),Boolean)
            End Get
            Set
                Me("HotTracking_Sync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HotTracking_SetBrit() As Boolean
            Get
                Return CType(Me("HotTracking_SetBrit"),Boolean)
            End Get
            Set
                Me("HotTracking_SetBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.4")>  _
        Public Property HotTracking_UsrBrit() As Double
            Get
                Return CType(Me("HotTracking_UsrBrit"),Double)
            End Get
            Set
                Me("HotTracking_UsrBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property General_AdvancedModeEnabled() As Boolean
            Get
                Return CType(Me("General_AdvancedModeEnabled"),Boolean)
            End Get
            Set
                Me("General_AdvancedModeEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property General_AccentSource() As Integer
            Get
                Return CType(Me("General_AccentSource"),Integer)
            End Get
            Set
                Me("General_AccentSource") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property General_SaveSettingsOnExit() As Boolean
            Get
                Return CType(Me("General_SaveSettingsOnExit"),Boolean)
            End Get
            Set
                Me("General_SaveSettingsOnExit") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property UI_ContextMenuStyle() As Integer
            Get
                Return CType(Me("UI_ContextMenuStyle"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://stackoverflow.com/questions/4580263/how-to-open-in-default-browser-in-c-sh"& _ 
            "arp")>  _
        Public ReadOnly Property ExternalResources_ProjectURL() As String
            Get
                Return CType(Me("ExternalResources_ProjectURL"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SyncSystemColors.My.MySettings
            Get
                Return Global.SyncSystemColors.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
